# Library names
SRC_FILE ?= library.cu
DST_FILE ?= libStaticLibOfFnsCUDAKernel

# Location of the CUDA Toolkit
CUDA_PATH ?= /usr/local/cuda/bin

# Target rules
all: build

build:
	$(MAKE) -C bin all

	
	